server:
  port: 9000

spring:
  application:
    name: turbine
logging:
  file: /log/${spring.application.name}.log

---
spring:
  profiles: single-eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8760/eureka
turbine:
  app-config: gateway,sample-aggregate
  cluster-name-expression: "'default'"
#  clusterNameExpression: "'default'"
