server:
  port: 8082

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
spring:
  application:
    name: sample-provider2

logging:
  file: /log/${spring.application.name}.log

---
spring:
  profiles: local
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8760/eureka

---
## 单个结点
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8760/eureka
spring:
  profiles: provider-s

---
## 单个结点
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka
spring:
  profiles: local

---

spring:
  profiles: sleuth-log
logging:
  level:
    org.springframework.cloud.sleuth: debug
