spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: sample-provider
          # lb:LoadBalancerClient
          uri: lb://sample-provider
          predicates:
            - Path=/sp/**
          filters:
            - StripPrefix=1
---
## 默认单个结点
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8760/eureka

---
## --- 高可用 ---

spring:
  profiles: ha
eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka, http://eureka-peer2:8762/eureka
