version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    ports:
      - "5601:5601"
    volumes:
      - /opt/ELK/conf/kibana.yml:/etc/kibana/kibana.yml
  logstash: #服务名称（不是容器名）
    image: docker.elastic.co/logstash/logstash:6.7.1 #使用的镜像
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: logstash #容器名称
    #挂载文件1.自定义配置文件 2.logstash启动配置文件 3.文件读取的挂载路径
    ports:
      - "5400:5400"
    volumes:
      - /opt/micro/ELK/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - /opt/ELK/conf/logstash.yml:/etc/logstash/logstash.yml
