version: '2.2'
services:
  eureka-peer1:
    image: sunbo/eureka-server:1.0-SNAPSHOT
    ports:
      - "9001:8761"
    environment:
      - spring.profiles.active=peer1
  eureka-peer2:
    image: sunbo/eureka-server:1.0-SNAPSHOT
    ports:
      - "9002:8762"
    environment:
      - spring.profiles.active=peer2
    depends_on:
      - eureka-peer1
  provider:
    image: sunbo/sample-provider:1.0-SNAPSHOT
    scale: 2
    depends_on:
      - eureka-peer1
      - eureka-peer2
    environment:
      - spring.profiles.active=provider-ha
  gateway:
    image: sunbo/gateway:1.0-SNAPSHOT
    scale: 1
    depends_on:
      - eureka-peer1
      - eureka-peer2
    environment:
      - spring.profiles.active=ha
    ports:
      - "3000:8080"
