version: '2'
services:
  eureka:
    image: sunbo/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "9000:8760"
  provider:
    image: sunbo/sample-provider:0.0.1-SNAPSHOT
    depends_on:
      - eureka
    environment:
      - spring.profiles.active=provider-s
  gateway:
    image: sunbo/gateway-SNAPSHOT
    depends_on:
      - eureka
