version: '2.2'
services:
  eureka-peer1:
    image: sunbo/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "9001:8761"
    environment:
      - spring.profiles.active=peer1
  eureka-peer2:
    image: sunbo/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "9002:8762"
    environment:
      - spring.profiles.active=peer2
    depends_on:
      - eureka-peer1
  provider:
    image: sunbo/sample-provider:0.0.1-SNAPSHOT
    scale: 2
    depends_on:
      - eureka-peer1
      - eureka-peer2
    environment:
      - spring.profiles.active=provider-ha
#    deploy:
#      mode: replicated
#      replicas: 3
  gateway:
    image: sunbo/gateway:0.0.1-SNAPSHOT
    scale: 1
    depends_on:
      - eureka-peer1
      - eureka-peer2
    environment:
      - spring.profiles.active=ha
    ports:
      - "10000:8080"
#    deploy:
#      mode: replicated
#      replicas: 2
