version: '2.2'
services:
  eureka:
    image: sunbo/eureka-server:1.0-SNAPSHOT
    ports:
      - "9000:8760"
    environment:
      - spring.profiles.active=single-eureka
    volumes:
      - /opt/micro/ELK/log/:/log/
    #  provider:
    #    image: sunbo/sample-provider:1.0-SNAPSHOT
    #    depends_on:
    #      - eureka
    #    environment:
    #      - spring.profiles.active=provider-s
  provider2:
    image: sunbo/sample-provider2:1.0-SNAPSHOT
    depends_on:
      - eureka
    environment:
      - spring.profiles.active=provider-s,sleuth-log
    #      scale: 2
    volumes:
      - /opt/micro/ELK/log/:/log/
  aggregate:
    image: sunbo/sample-aggregate:1.0-SNAPSHOT
    depends_on:
      - eureka
    ports:
      - "4001:8080"
    environment:
      - spring.profiles.active=provider-s,sleuth-log
    volumes:
      - /opt/micro/ELK/log/:/log/
  gateway:
    image: sunbo/gateway:1.0-SNAPSHOT
    depends_on:
      - eureka
    ports:
      - "3000:8080"
    environment:
      - spring.profiles.active=single-eureka,route-agg
    volumes:
      - /opt/micro/ELK/log/:/log/
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.7.1
    user: root

    volumes:
#      - /home/sunb/stroage/dockerVolumn/micro/filebeat/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#      - /home/sunb/stroage/dockerVolumn/micro/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /opt/micro/ELK/config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml

