version: '2.2'
services:
#  eureka:
#    image: sunbo/eureka-server:1.0-SNAPSHOT
#    ports:
#      - "9000:8760"
#    environment:
#      - spring.profiles.active=single-eureka
#  #  provider:
#  #    image: sunbo/sample-provider:1.0-SNAPSHOT
#  #    depends_on:
#  #      - eureka
#  #    environment:
#  #      - spring.profiles.active=provider-s
#  provider2:
#    image: sunbo/sample-provider2:1.0-SNAPSHOT
#    depends_on:
#      - eureka
#    environment:
#      - spring.profiles.active=provider-s,sleuth-log
#    scale: 2
#  aggregate:
#    image: sunbo/sample-aggregate:1.0-SNAPSHOT
#    depends_on:
#      - eureka
#    ports:
#      - "4001:8080"
#    environment:
#      - spring.profiles.active=provider-s,sleuth-log
#  gateway:
#    image: sunbo/gateway:1.0-SNAPSHOT
#    depends_on:
#      - eureka
#    ports:
#      - "3000:8080"
#    environment:
#      - spring.profiles.active=single-eureka,route-agg
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    ports:
      - "5601:5601"
    volumes:
      - /opt/ELK/conf/kibana.yml:/etc/kibana/kibana.yml
  logstash: #服务名称（不是容器名）
    image: logstash  #使用的镜像
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: logstash #容器名称
    #挂载文件1.自定义配置文件 2.logstash启动配置文件 3.文件读取的挂载路径
    volumes:
      - /opt/ELK/conf/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - /opt/ELK/conf/logstash.yml:/etc/logstash/logstash.yml
      - /opt/ELK/conf/1.txt:/etc/logstash/1.txt
