GET http://localhost:8080/v
Accept: application/json

###
GET http://localhost:8080/actuator/health
Accept: application/vnd.spring-boot.actuator.v2+json

###
GET http://localhost:8080/actuator
Accept: application/vnd.spring-boot.actuator.v2+json

###
GET http://localhost:8080/actuator/info
Accept: application/vnd.spring-boot.actuator.v2+json

###
GET http://localhost:8080/actuator/configprops
Accept: application/vnd.spring-boot.actuator.v2+json

###
GET http://localhost:8080/actuator/mappings
Accept: application/vnd.spring-boot.actuator.v2+json

###
GET http://localhost:8080/actuator/evn
Accept: application/json
###

#自己的接口
GET http://localhost:9001/v
Accept: application/json

###

