filebeat:
  config:
    modules:
      path: ${path.config}/modules.d/*.yml
      reload:
        enabled: false
  inputs:
    - paths:
        - "/opt/micro/ELK/log/*"
      type: log
      enabled: true
      tags: [micro]
output:
  logstash:
    hosts: ["192.168.200.140:5044"]
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
